
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "nombre": "Lucas Test",
    "email": "lucas@test.com",
    "clave": "123456",
    "ubicacion": "Madrid"
}

### Prueba de Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "lucas@test.com",
    "clave": "123456"
}

### Obtener Perfil (Ruta Protegida)
GET http://localhost:3000/api/users/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJsdWNhc0B0ZXN0LmNvbSIsImlhdCI6MTc3MzEyOTMzNiwiZXhwIjoxNzczMTMyOTM2fQ.uvTGaOY1A-rcPQ0RBF410bjVxpXAopo9TV53E3dFdyM

### Prueba de Comercio
POST http://localhost:3000/api/comercios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJsdWNhc0B0ZXN0LmNvbSIsImlhdCI6MTc3MzEyOTMzNiwiZXhwIjoxNzczMTMyOTM2fQ.uvTGaOY1A-rcPQ0RBF410bjVxpXAopo9TV53E3dFdyM

{
    "nombre": "Comercio Test",
    "descripcion": "Descripción del comercio de prueba",
    "categoria": "Ropa",
    "contacto": "600000000",
    "direccion": "Calle Mayor 1"
}

### Agregar un producto a un comercio específico
POST http://localhost:3000/api/productos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJsdWNhc0B0ZXN0LmNvbSIsImlhdCI6MTc3MzEyOTMzNiwiZXhwIjoxNzczMTMyOTM2fQ.uvTGaOY1A-rcPQ0RBF410bjVxpXAopo9TV53E3dFdyM   

{
    "nombre": "Producto Test",
    "descripcion": "Descripción del producto de prueba",
    "precio": 19.99,
    "stock": 100,
    "imagen": "url_de_la_imagen.jpg",
    "id_comercio": 4
}

### Actualizar un producto existente
PUT http://localhost:3000/api/productos/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJsdWNhc0B0ZXN0LmNvbSIsImlhdCI6MTc3MzEyOTMzNiwiZXhwIjoxNzczMTMyOTM2fQ.uvTGaOY1A-rcPQ0RBF410bjVxpXAopo9TV53E3dFdyM

{
  "nombre": "Nombre Actualizado",
  "descripcion": "Nueva descripción del producto",
  "precio": 25.50,
  "stock": 50,
  "imagen": "nueva_imagen.jpg"
}

### Eliminar un producto existente
DELETE http://localhost:3000/api/productos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJsdWNhc0B0ZXN0LmNvbSIsImlhdCI6MTc3MzEzNTg3OCwiZXhwIjoxNzczMTM5NDc4fQ.X8IYUtqEb4b6kdWdfzrEhDp6Jyd0b-rlrlG5SddEKX4
